daftarzild/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.conf.urls.static import static
from django.conf import settings

from .views import (
	home,
	)

urlpatterns = [
    # Examples:
    # url(r'^$', 'daftarzild.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home, name='home'),
    url(r'^dz/', include("dzadmin.urls", namespace='dzadmin')),
    url(r'^news/', include("posts.urls", namespace='posts')),
    url(r'^comments/', include("comments.urls", namespace='comments')),



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

urlpatterns = [
	url(r'^$', post_list, name='allnews'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

templates/band members.html
{% extends "index.html" %}
{% load staticfiles %}
{% block body %}
<!-- Page Content -->
        <div class="col-lg-12 member-name">
            <h1>NAKUL SHARMA</h1>
        </div>
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    
    <!-- /.row -->
<div class='col-sm-8 col-sm-offset-2' style="background-color:white; border-radius: 10px;">
    <section>
        <div class="band-member-photo">
            <img src="{% static "images/hetfield.jpeg" %}">
        </div>
        <div class="band-member-stats">
            <dl>
                <dt>Born</dt>
                <dd>2nd August 1991</dd>
            </dl>
        </div>
    </section>

    <!-- Content Row -->
    <h3>Story</h3>
    <hr/>

    <div class="band-member-story">
        <div class="col-lg-12">
            <p>With a fierce, unbending dedication to his art, and the uncanny ability to empathize with millions, vocalist and guitarist James Hetfield is an inspirational focal point for Metallica. Born to a truck driver and light opera singer in Los Angeles, the Hetfield family’s Christian Science beliefs played a large part in James’ early life, proving a powerful catalyst for many of Hetfield’s early lyrics.</p>
            <p>James was nine years old when he first took piano lessons, before taking on his brother David’s drums and finally picking up a guitar in his pre-teens. Fueled by the likes of Black Sabbath, Led Zeppelin and Thin Lizzy, James quickly set about the task of channeling his creativity and angst in his first band, Obsession. Phantom Lord and Leather Charm were further stepping stones (James’ pal Hugh Tanner playing guitar in both) with Ron McGovney being convinced to play bass in …Charm. Soon the band was forced to call it quits, Tanner departing, but not before introducing James to Lars Ulrich. Needless to say, those two would go on to form Metallica. Tentative in his early days at the mic (there had been talk of Armored Saint’s John Bush coming in as the singer), James settled into his stride between Ride The Lightning and Master of Puppets, banishing all thoughts of anyone else as front man, and helping propel the band to international stardom. The path has not been without its trials and tribulations. He has been physically “broken, beat and scarred” during his career, from breaking an arm (twice!) in 1986 and 1987 to surviving a full-flame pyro immersion in 1992… none of which derailed him for too long. And in 2001, James found himself in need of a self-imposed lay-off from Metallica, going to rehab and engaging in some core personal developments that allowed him to return stronger, clearer and fitter than ever.</p>

            <p>Along with Lars, James is the main songwriter in Metallica, co-creating the framework and structure for most Metalli-material. He is also responsible for all lyrics, many of which touch on personal feelings and struggles over the decades, and which have seen him find empathy with millions of fans. When he’s not writing, singing or playing, James enjoys spending time with his wife Francesca and their three children Cali, Castor and Marcella. James also continues to enjoy his classic car collection, a variety of outdoor activities, watching all manner of Bay Area sports teams from his favorite Oakland Raiders to the San Francisco Giants and San Jose Sharks and collecting older guitars (particularly those from 1963). James also likes to get grimy in his own “shop” on various projects and he continues to enjoy drawing and sketching, still penning some of the logos and t-shirt designs fans enjoy today.</p>
        </div>
    </div>
    <!-- /.row -->

    <hr>

</div>
</div>


<div class="col-lg-12 member-name">
            <h1>Pranay</h1>
        </div>
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    
    <!-- /.row -->
<div class='col-sm-8 col-sm-offset-2' style="background-color:white; border-radius: 10px;">
    <section>
        <div class="band-member-photo">
            <img src="{% static "images/hetfield.jpeg" %}">
        </div>
        <div class="band-member-stats">
            <dl>
                <dt>Born</dt>
                <dd>2nd August 1991</dd>
            </dl>
        </div>
    </section>

    <!-- Content Row -->
    <h3>Story</h3>
    <hr/>

    <div class="band-member-story">
        <div class="col-lg-12">
            <p>With a fierce, unbending dedication to his art, and the uncanny ability to empathize with millions, vocalist and guitarist James Hetfield is an inspirational focal point for Metallica. Born to a truck driver and light opera singer in Los Angeles, the Hetfield family’s Christian Science beliefs played a large part in James’ early life, proving a powerful catalyst for many of Hetfield’s early lyrics.</p>
            <p>James was nine years old when he first took piano lessons, before taking on his brother David’s drums and finally picking up a guitar in his pre-teens. Fueled by the likes of Black Sabbath, Led Zeppelin and Thin Lizzy, James quickly set about the task of channeling his creativity and angst in his first band, Obsession. Phantom Lord and Leather Charm were further stepping stones (James’ pal Hugh Tanner playing guitar in both) with Ron McGovney being convinced to play bass in …Charm. Soon the band was forced to call it quits, Tanner departing, but not before introducing James to Lars Ulrich. Needless to say, those two would go on to form Metallica. Tentative in his early days at the mic (there had been talk of Armored Saint’s John Bush coming in as the singer), James settled into his stride between Ride The Lightning and Master of Puppets, banishing all thoughts of anyone else as front man, and helping propel the band to international stardom. The path has not been without its trials and tribulations. He has been physically “broken, beat and scarred” during his career, from breaking an arm (twice!) in 1986 and 1987 to surviving a full-flame pyro immersion in 1992… none of which derailed him for too long. And in 2001, James found himself in need of a self-imposed lay-off from Metallica, going to rehab and engaging in some core personal developments that allowed him to return stronger, clearer and fitter than ever.</p>

            <p>Along with Lars, James is the main songwriter in Metallica, co-creating the framework and structure for most Metalli-material. He is also responsible for all lyrics, many of which touch on personal feelings and struggles over the decades, and which have seen him find empathy with millions of fans. When he’s not writing, singing or playing, James enjoys spending time with his wife Francesca and their three children Cali, Castor and Marcella. James also continues to enjoy his classic car collection, a variety of outdoor activities, watching all manner of Bay Area sports teams from his favorite Oakland Raiders to the San Francisco Giants and San Jose Sharks and collecting older guitars (particularly those from 1963). James also likes to get grimy in his own “shop” on various projects and he continues to enjoy drawing and sketching, still penning some of the logos and t-shirt designs fans enjoy today.</p>
        </div>
    </div>
    <!-- /.row -->

    <hr>

</div>
</div>
<div class="col-lg-12 member-name">
            <h1>PRATEEK ANAND</h1>
        </div>
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    
    <!-- /.row -->
<div class='col-sm-8 col-sm-offset-2' style="background-color:white; border-radius: 10px;">
    <section>
        <div class="band-member-photo">
            <img src="{% static "images/hetfield.jpeg" %}">
        </div>
        <div class="band-member-stats">
            <dl>
                <dt>Born</dt>
                <dd>2nd August 1991</dd>
            </dl>
        </div>
    </section>

    <!-- Content Row -->
    <h3>Story</h3>
    <hr/>

    <div class="band-member-story">
        <div class="col-lg-12">
            <p>With a fierce, unbending dedication to his art, and the uncanny ability to empathize with millions, vocalist and guitarist James Hetfield is an inspirational focal point for Metallica. Born to a truck driver and light opera singer in Los Angeles, the Hetfield family’s Christian Science beliefs played a large part in James’ early life, proving a powerful catalyst for many of Hetfield’s early lyrics.</p>
            <p>James was nine years old when he first took piano lessons, before taking on his brother David’s drums and finally picking up a guitar in his pre-teens. Fueled by the likes of Black Sabbath, Led Zeppelin and Thin Lizzy, James quickly set about the task of channeling his creativity and angst in his first band, Obsession. Phantom Lord and Leather Charm were further stepping stones (James’ pal Hugh Tanner playing guitar in both) with Ron McGovney being convinced to play bass in …Charm. Soon the band was forced to call it quits, Tanner departing, but not before introducing James to Lars Ulrich. Needless to say, those two would go on to form Metallica. Tentative in his early days at the mic (there had been talk of Armored Saint’s John Bush coming in as the singer), James settled into his stride between Ride The Lightning and Master of Puppets, banishing all thoughts of anyone else as front man, and helping propel the band to international stardom. The path has not been without its trials and tribulations. He has been physically “broken, beat and scarred” during his career, from breaking an arm (twice!) in 1986 and 1987 to surviving a full-flame pyro immersion in 1992… none of which derailed him for too long. And in 2001, James found himself in need of a self-imposed lay-off from Metallica, going to rehab and engaging in some core personal developments that allowed him to return stronger, clearer and fitter than ever.</p>

            <p>Along with Lars, James is the main songwriter in Metallica, co-creating the framework and structure for most Metalli-material. He is also responsible for all lyrics, many of which touch on personal feelings and struggles over the decades, and which have seen him find empathy with millions of fans. When he’s not writing, singing or playing, James enjoys spending time with his wife Francesca and their three children Cali, Castor and Marcella. James also continues to enjoy his classic car collection, a variety of outdoor activities, watching all manner of Bay Area sports teams from his favorite Oakland Raiders to the San Francisco Giants and San Jose Sharks and collecting older guitars (particularly those from 1963). James also likes to get grimy in his own “shop” on various projects and he continues to enjoy drawing and sketching, still penning some of the logos and t-shirt designs fans enjoy today.</p>
        </div>
    </div>
    <!-- /.row -->

    <hr>

</div>
</div>
<!-- /.container -->
{% endblock %}

templates/contact.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block body %}

    <!-- Page Content -->
    

    <div class="col-lg-12 member-name">
                <h3>Send us a Message</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <form method="POST" action="#"> {% csrf_token %}
                    {{ form|crispy }}
                    <input type='submit' value='Send message' class='btn btn-primary'>
                </form>
            </div>

        </div>

    </div>
    <!-- /.container -->

{% endblock %} 

templates/homepagenews.html
{% extends "index.html" %}
{% load staticfiles %}
{% block homepagenews %}
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">News</h1>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-12">
                {% for obj in object_list %}
                <!-- First Blog Post -->
                <div class='news-card'>
                
                    {% if obj.image %}
                    <div class='news-image' style="background-image:url('{{ STATIC_URL }}{{ obj.image.url }}')">
                    </div>
                    {% endif %}
                    <div class='news-details'>
                        <h2>
                            <a class='news-title' href="{{ obj.get_absolute_url }}">{{ obj.title }}</a>
                        </h2>
                        <p><i class="fa fa-clock-o"></i> {{ obj.timestamp }}</p>
                        <hr>
                        <p class="">{{ obj.get_markdown|truncatechars_html:420 }}</p>
                        <a class="btn btn-primary" href="{{ obj.get_absolute_url }}">Read More <i class="fa fa-angle-right"></i></a>
                    </div>
                    <hr>


                </div>
                <hr>

                {% endfor %}
                                <!-- Pager -->
                 <!-- Pagination -->
                     <div class="pagination">
                        <span class="step-links">
                            {% if object_list.has_previous %}
                                <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
                            {% endif %}

                            <span class="current">
                                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                            </span>

                            {% if object_list.has_next %}
                                <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                            {% endif %}
                        </span>
                    </div>
                

            </div>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>DaftarZild.com</title>
    

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "css/index.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->   

</head>

<body style="background-color:lightgrey;">

    <!-- Header Carousel -->
    
    	<!-- Navigation -->
	    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	            <!-- Collect the nav links, forms, and other content for toggling -->
	            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	                <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href='{% url "home" %}'>Login</a>
                        </li>
                        <li>
                            <a href='{% url "home" %}'>Sign Up</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
	                    <li>
	                        <a href='{% url "home" %}'>Home</a>
	                    </li>
	                    <li>
	                        <a href={% url "dzadmin:contact" %}>Contact</a>
	                    </li>
                        <li>
                            <a href={% url "posts:allnews" %}>News</a>
                        </li>
                        <li>
                            <a href={% url "dzadmin:music" %}>Music</a>
                        </li>
                        <li>
                            <a href={% url "dzadmin:music" %}>Media</a>
                        </li> 
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Band <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href={% url "dzadmin:bandmembers" %}>Band Members</a>
                                </li>
                                <li>
                                    <a href="blog-home-2.html">History</a>
                                </li>
                            </ul>
                        </li> 
	                </ul>
	            </div>
	            <!-- /.navbar-collapse -->
	    </nav>
    {% block body %}
	<div class= "bg">
        <div class="container">
					<div class="banner-info text-center">
						<h1>Daftar Zild</h1>
					
					</div>
		</div>
    </div>
    <div class="col-lg-12 member-name">
                <h1>News</h1>
    </div>

    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
            
        <!-- /.row -->

        {# homepagenews #}


        <br>
                <div class='home-news-card'>
                    <div class='home-newscard-image'>
                        <div id="myCarousel" class="carousel" >
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                              <li data-target="#myCarousel" data-slide-to="1"></li>
                              <li data-target="#myCarousel" data-slide-to="2"></li>
                            </ol>

                            <!-- Wrapper for slides -->
                            
                                
                                <div class="carousel-inner custom_carousel" role="listbox">
                                    {% for obj in object_list %}
                                        {% if forloop.first %}
                                            <div class="item active">
                                                <img src="{{ obj.image.url }}" alt="">
                                            </div>
                                        {% else %}
                                        <div class="item homenewsimage">
                                            <img src="{{ obj.image.url }}" alt="" >
                                        </div>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                        </div>
                    </div>

                    <div class='home-newscard-content'>
                        <div id="myCarousel2" class="carousel" >
                            <div class="carousel-inner custom_carousel" role="listbox">
                                {% for obj in object_list %}
                                    {% if forloop.first %}
                                    <div class="item active">
                                        <a href="{{ obj.get_absolute_url }}"><h3>{{ obj.title }}</h3></a>
                                    </div>
                                    {% else %}
                                    <div class="item">
                                        <a href="{{ obj.get_absolute_url }}"><h3>{{ obj.title }}</h3></a>
                                        <p>{{ obj.get_markdown|truncatechars_html:220 }}
                                    </div>
                                    {% endif %}    
                                {% endfor %}
                                <a class="btn btn-t-external card-external-link" href="">Read More</a>

                            </div>

                        </div>
                    </div>
                    
                </div>
        
                {% for news in othernews %}
                    <div class="col-md-3 othernews-card well">
                        <a href="{{news.get_absolute_url}}"><div class="well-image" style="background-image:url('{{ STATIC_URL }}{{ news.image.url }}')">
                    </div>
                    <div class='well-content'>
                        <h4>{{ news.title|truncatechars_html:40  }}</h4>
                    </div>
                    <!-- /.row -->
                    </div>
                {% endfor %}


                    



        <!-- /.row -->

    </div>

    {% endblock %}

    {% block homepagemedia %}
    {% endblock %}
    {% block gigsdates %}
    {% endblock %}
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>
    <!-- /.container -->
    <!-- jQuery -->
   

    <!-- Script to Activate the Carousel -->
    
<script   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>
<script type="text/javascript" src='{% static "js/index.js" %}'></script>


<script type="text/javascript">
    $(document).ready(function(){ 
        
        var carousel1 = $('#myCarousel').carousel();
        var carousel2= $('#myCarousel2').carousel();
        
        carousel1.on('slide.bs.carousel', function(event) {
            var to = $(event.relatedTarget).index();
            carousel2.carousel(to);
        });


    $(".comment-reply").hide()

    $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        console.log($(this).parent().next());
        $(this).parent().next(".comment-reply").fadeToggle();
        console.log('inside jquery');
    })



    })

</script>

</body>


</html>

templates/music.html
{% extends "index.html" %}
{% block body %}
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">All Tracks</h1>
            </div>
        
        <!-- /.row -->
        <div class='col-lg-8'>
        <iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?visual=true&url=https%3A%2F%2Fapi.soundcloud.com%2Fplaylists%2F218602546&show_artwork=true&oauth_token=1-254294-177435657-4be2fe9060d3b&client_id=c3ba3b862a2ff085f07e051a79767aa3"></iframe>
        </div>

        </div>

        <hr>

{% endblock %}

templates/newsdetail.html
{% extends "index.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block body %}
    <!-- Page Content -->
    <div class="col-lg-12 member-name">
                <h1>{{ instance.title }}</h1>
                <p><i class="fa fa-clock-o"></i> {{ instance.timestamp }}</p>
    </div>
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
           

        <!-- Content Row -->
        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Preview Image -->
                {% if instance.image %}
                <img class="img-responsive" src="{{instance.image.url}}" alt="">
                {% endif %}



                <!-- Post Content -->

                <div class="news_content">
                    {{ instance.get_markdown }}
                </div>

                <hr>

                <!-- Blog Comments -->

                <!-- Comments Form -->
                <div>
                        <p class='lead'>Comments</p>
                        {% if request.user.is_authenticated %}
                        <form method="POST" action="."> {% csrf_token %}
                            {{ comment_form|crispy }}
                            <input type='submit' value='Post comment' class='btn btn-default'>
                        </form>
                        {% else %}
                        <p>You must login to comment </p>
                        {% endif %}
                        <hr/>
                        {% for comment in comments %}

                        <blockquote>
                          
                          <p>{{ comment.content }}</p>
                          <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} replies | {% endif %} <a class='comment-reply-btn' href='#'>Reply</a> | <a class='' href='{{ comment.get_absolute_url }}'>Thread</a></footer>
                          
                          <div class='comment-reply'>
                              
                              {% for child_comment in comment.children %}
                                <blockquote>
                                <p>{{ child_comment.content }}</p>
                                <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
                                </blockquote>
                             {% endfor %}
                             
                            {% if request.user.is_authenticated %}
                            <form method="POST" action="."> {% csrf_token %}
                                {{ comment_form|crispy }}
                                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                                <input type='submit' value='Reply' class='btn btn-default'>
                            </form>
                            {% else %}
                            <p>You must login to comment </p>
                            {% endif %}
                        
                        </div>

                        </blockquote>

                        {% endfor %}
                </div>



                <!-- Posted Comments -->

               

            

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">
                <!-- Blog Categories Well -->
                <h3>Recent News</h3>
                {% for obj in news_objects %}
                <div class="well ">
                    <a href="{{obj.get_absolute_url}}"><div class="well-image" style="background-image:url('{{ STATIC_URL }}{{ obj.image.url }}')">
                    
                    </div>
                    <div class='well-content'>
                        <h4>{{ obj.title }}</h4>
                    </div>
                    <!-- /.row -->
                </div>
                {% endfor %}

            </div>

        </div>
        <!-- /.row -->

        <hr>

    </div>
    <!-- /.container -->
{% endblock %}

templates/newshome.html
{% extends "index.html" %}
{% load staticfiles %}
{% block body %}
    <!-- Page Content -->
    <div class="col-lg-12 member-name">
                <h1 >News</h1>
            </div>
    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-12">
                {% for obj in object_list %}
                <!-- First Blog Post -->
                <div class='news-card'>
                
                    {% if obj.image %}
                    <div class='news-image' style="background-image:url('{{ STATIC_URL }}{{ obj.image.url }}')">
                    </div>
                    {% endif %}
                    <div class='news-details'>
                        <h2>
                            <a class='news-title' href="{{ obj.get_absolute_url }}">{{ obj.title }}</a>
                        </h2>
                        <p><i class="fa fa-clock-o"></i> {{ obj.timestamp }}</p>
                        <hr>
                        <p class="">{{ obj.get_markdown|truncatechars_html:420 }}</p>
                        <a class="btn btn-primary" href="{{ obj.get_absolute_url }}">Read More <i class="fa fa-angle-right"></i></a>
                    </div>
                    <hr>


                </div>
                <hr>

                {% endfor %}
                                <!-- Pager -->
                 <!-- Pagination -->
                     <div class="pagination">
                        <span class="step-links">
                            {% if object_list.has_previous %}
                                <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
                            {% endif %}

                            <span class="current">
                                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                            </span>

                            {% if object_list.has_next %}
                                <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                            {% endif %}
                        </span>
                    </div>
                

            </div>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
{% endblock %}